### ISSUE TITLE
TwoFaController uses use RobThree\Auth\TwoFactorAuth; which does not exists

### ISSUE THREAD

**Issue by rabol** [dcblogdev/laravel-admintw#11]
in TwoFaController there is this:
```
use RobThree\Auth\TwoFactorAuth;
```

however that does not exists.

**Comment by dcblogdev** [comment]
it is, it sounds like you haven't ran `composer update`

these are the steps: 

1) install a laravel project
2) install this package
3) install admintw using `php artisan admintw:install`
4) run composer update to install package dependencies 
5) install NPM and run `npm install && npm run dev`

I realised I didn't mention the composer step in the read me
