### ISSUE TITLE
Dark/Light mode switcher

### ISSUE THREAD

**Issue by mai1237** [dcblogdev/laravel-admintw#13]
It would be very nice to include a dark-light switcher

**Comment by dcblogdev** [comment]
dark mode is currently based on the OS, I agree it would be nice to have a toggle option.

**Comment by syah769** [comment]
How can i set default to light mode? even my OS is dark mode, but i want my admintw light mode

**Comment by dcblogdev** [comment]
add `darkMode: 'class',` to `tailwind.config.js` then run `npm run dev` 

this will default to light mode and relies on a `dark` class to trigger dark mode.

**Comment by syah769** [comment]
> add `darkMode: 'class',` to `tailwind.config.js` then run `npm run build`
> 
> this will default to light mode and relies on a `dark` class to trigger dark mode.

thanks, success
