### ISSUE TITLE
Permissions- Working on Listing records not  for edit records

### ISSUE THREAD

**Issue by rkishir** [dcblogdev/laravel-admintw#19]
I created one component on which I perform CRUD operation and add permission entireties in permissions table and assign permission to add,view,edit,delete to newly created Role 

Permissions: table
![image](https://user-images.githubusercontent.com/16318440/217323986-162a986c-5ba5-4160-95bf-971f358f2519.png)

Regions listing component: abort_if_cannot('view_regions');  works fine her if remove permission then abort the request if add then show view page all fine but 
![image](https://user-images.githubusercontent.com/16318440/217324461-28761699-0b6d-45e2-a0db-0e36ad7eecf2.png)

On Edit component abort_if_cannot('edit_regions'); not worked  it also show permission  "401 - You do not have the correct permissions." even I assigned edit permission to that role. 
![image](https://user-images.githubusercontent.com/16318440/217325605-07e254c4-1dbb-4ab8-8007-dc13166b24ae.png)

My Region Model:
![image](https://user-images.githubusercontent.com/16318440/217326515-df14141b-7767-4ece-b266-93ba3432eb43.png)

**Comment by dcblogdev** [comment]
the permissions get loaded from the Base component, it looks like your edit class is extending from `App\Http\Livewire\Base` is the correct?

**Comment by rkishir** [comment]
yes its correct. Also on left navigation it lost all permissions on edit component  page. 
![image](https://user-images.githubusercontent.com/16318440/219038545-4156c6b6-7765-4777-9536-5beeabecc534.png)

**Comment by rkishir** [comment]
Its working on users component. Must be some wrong but not able to figure out in my components.

**Comment by rkishir** [comment]
Its solved. Issue was I did not add      parent::mount();  in mount function. 
public function mount(): void
    {
        parent::mount();
        $this->name = $this->region->name ?? '';
    }

**Comment by rkishir** [comment]
Now on some cases I am getting if I added  abort_if_cannot('add_regions'); function
![image](https://user-images.githubusercontent.com/16318440/219075134-70f9897d-4408-463b-9681-11276e110ec8.png)

**Comment by dcblogdev** [comment]
I'm having trouble replicating this, can you post the stack trace from the error log.

I'm considering working on a version 3 that uses blade for the core controllers which can ensure role and settings apply to all pages, in retrospect doing it all in Livewire I think was a mistake.
