### ISSUE TITLE
Can't issue Sanctum tokens as it has incorrect field type

### ISSUE THREAD

**Issue by LucidTheStick** [dcblogdev/laravel-admintw#2]
The default 2019_12_14_000001_create_personal_access_tokens_table migration uses the morphs field type.  This creates a normal VARCHAR and BIGINT fields for the user.id relation.  As these are now UUID, it cannot put the UUID in the BIGINT field.  Field needs to be changed post migrate from BIGINT to CHAR(36).  This should be fixed in migrations.

Steps to reproduce error:
1) Fresh Install
2) Edit routes/web.php
use Illuminate\Http\Request;
```
//authenticated
Route::middleware(['web', 'auth', 'activeUser', 'IpCheckMiddleware'])->prefix('admin')->group(function () {
   Route::get('/tokens/create', function (Request $request) {
        $token = $request->user()->createToken("Auto Generated");
     
        return ['token' => $token->plainTextToken];
    });
```
3) Issue a get after logging in to http://127.0.0.1:8000/admin/tokens/create

**Comment by dcblogdev** [comment]
I've changed these with a new release.
