### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by bulentsakarya** [dcblogdev/laravel-admintw#22]
After first account, other accounts role could be user.

**Comment by bulentsakarya** [comment]
After the first user becomes a member, the role of other users becomes admin. Can you change them to user ?

**Comment by dcblogdev** [comment]
When you invite users you specify which role they should have

![CleanShot 2023-03-14 at 10 52 44](https://user-images.githubusercontent.com/1018170/224979458-4a026987-8c27-48f2-a7b7-f12ed377cbc0.png)

You can add/remove roles to users by editing the user and checking/unchecking their roles

![CleanShot 2023-03-14 at 10 53 10](https://user-images.githubusercontent.com/1018170/224979602-b660e287-9364-4dfc-b1aa-8521a93b1049.png)

**Comment by bulentsakarya** [comment]
I added the following code to the RegisteredUserController.php file.

```
        if(User::count() > 1) {
            $user->assignRole('user');
        } else {
            $user->assignRole('admin');
        }
```

But I got the following error.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`panel`.`audit_trails`, CONSTRAINT `audit_trails_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `audit_trails` (`user_id`, `title`, `link`, `reference_id`, `section`, `type`, `id`, `updated_at`, `created_at`) values (565de4b7-5e53-45e0-b9d6-e27be0d40dff, registered Bülent, , 0, Auth, Register, 79a7b1d7-81ee-428f-ae8f-e4b4c1f7765b, 2023-03-14 10:56:37, 2023-03-14 10:56:37))

**Comment by bulentsakarya** [comment]
I added the following code to the RegisteredUserController.php file.

```
        if(User::count() > 1) {
            $user->assignRole('user');
        } else {
            $user->assignRole('admin');
        }
```

But I got the following error.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`panel`.`audit_trails`, CONSTRAINT `audit_trails_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `audit_trails` (`user_id`, `title`, `link`, `reference_id`, `section`, `type`, `id`, `updated_at`, `created_at`) values (565de4b7-5e53-45e0-b9d6-e27be0d40dff, registered Bülent, , 0, Auth, Register, 79a7b1d7-81ee-428f-ae8f-e4b4c1f7765b, 2023-03-14 10:56:37, 2023-03-14 10:56:37))

**Comment by bulentsakarya** [comment]
I added the following code to the RegisteredUserController.php file.

```
        if(User::count() > 1) {
            $user->assignRole('user');
        } else {
            $user->assignRole('admin');
        }
```

But I got the following error.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`panel`.`audit_trails`, CONSTRAINT `audit_trails_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `audit_trails` (`user_id`, `title`, `link`, `reference_id`, `section`, `type`, `id`, `updated_at`, `created_at`) values (565de4b7-5e53-45e0-b9d6-e27be0d40dff, registered Bülent, , 0, Auth, Register, 79a7b1d7-81ee-428f-ae8f-e4b4c1f7765b, 2023-03-14 10:56:37, 2023-03-14 10:56:37))

**Comment by dcblogdev** [comment]
Oh I see, the audits table has a reference_id column that's expecting a foreign key.

Since the reference can belong to any table containing it I think was a mistake.

I will change `$table->foreignUuid('reference_id')->nullable();` in the migration to `$table->uuid('reference_id');`

This will allow the reference to use any UUID column
