### ISSUE TITLE
Error when registering new user

### ISSUE THREAD

**Issue by blockhunts** [dcblogdev/laravel-admintw#23]
On Register page, after I filled the input and click register.
I got the following error. (sorry if the text is in japanese)
![image](https://user-images.githubusercontent.com/38546608/225211468-2658b16d-d833-47fc-bbd0-abcebdbb487a.png)

Which means [operand type mismatch: int is incompatible with uniqueidentifier]

But when I checked the users table, new data safely created and I can login

**Comment by dcblogdev** [comment]
I think this was caused by the foreign key setup for the reference_id in audit_trails table, I've now changed this to use a UUID column instead as there are times it can be blank.

Let me know if you come across anything else, thanks.
