### ISSUE TITLE
php artisan migrate... Connection with Postgresql - 2 FAILs

### ISSUE THREAD

**Issue by saamondino** [dcblogdev/laravel-admintw#25]
Hello,

I have a **connection with Postgresql**, when running `php artisan migrate`, 2 errors appear:

 `2014_10_12_000000_create_users_table .................................................................... 139ms FAIL`

   ```
Illuminate\Database\QueryException

  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "("
LINE 1: ALTER TABLE users ADD FULLTEXT (name, email)
                                       ^ (Connection: pgsql, SQL: ALTER TABLE users ADD FULLTEXT (name, email))
```

AND ..

`2021_05_08_200523_create_notifications_table ............................................................. 41ms FAIL`

  ```
 Illuminate\Database\QueryException

  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "0" (Connection: pgsql, SQL: create table "notifications" ("id" uuid not null, "title" varchar(255) not null, "assigned_to_user_id" uuid not null, "assigned_from_user_id" uuid not null default '0', "link" varchar(255) null, "viewed" boolean null, "viewed_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null))
```

My Version of Postgresql => 10.23,  PHP =>8.2.4 and Laravel 10.

Can you guide me to solve the problems?

Regards.

Sergio

**Comment by dcblogdev** [comment]
this is due to the application using full text which postgres does not support, do you can remove these from the migrations:

```php
if (config('app.env') !== 'testing') {
    DB::statement('ALTER TABLE users ADD FULLTEXT (name, email)');
}
```

bear in mind the search component won't work as it uses this:

```php
$results = $query->selectRaw('*, MATCH ('.$fields.') AGAINST (? IN BOOLEAN MODE)', ['*'.$search.'*'])
->whereRaw('MATCH ('.$fields.') AGAINST (? IN BOOLEAN MODE)', ['*'.$search.'*'])
->take(10)
->get();
```

To avoid this use MySQL database. 

I'm going to look at swapping out full text to maybe use a dedicate search service instead.
