### ISSUE TITLE
Livewire 3 Update Please

### ISSUE THREAD

**Issue by fixcoderu** [dcblogdev/laravel-admintw#29]
Hello!
I am trying to upgrade Livewire to version 3.xx, but I get a lot of dependency-related errors:

  Problem 1
    - pestphp/pest-plugin-livewire v2.0.0 requires livewire/livewire ^2.12.3 -> found livewire/livewire[v2.12.3, v2.12.4, v2.12.5, v2.12.6] but it conflicts with you
r root composer.json require (^3.0).
    - Root composer.json requires pestphp/pest-plugin-parallel ^1.2 -> satisfiable by pestphp/pest-plugin-parallel[v1.2.0, v1.2.1].
    - Root composer.json requires pestphp/pest-plugin-livewire ^2.0 -> satisfiable by pestphp/pest-plugin-livewire[v2.0.0, v2.1.0].
    - pestphp/pest-plugin-livewire v2.1.0 requires pestphp/pest ^2.9.1 -> satisfiable by pestphp/pest[v2.16.0, v2.16.1].
    - pestphp/pest v2.16.1 requires pestphp/pest-plugin ^2.1.1 -> satisfiable by pestphp/pest-plugin[v2.1.1].
    - pestphp/pest v2.16.0 requires pestphp/pest-plugin ^2.0.1 -> satisfiable by pestphp/pest-plugin[v2.0.1, v2.1.0, v2.1.1].
    - You can only install one version of a package, so only one of these can be installed: pestphp/pest-plugin[v1.0.0, v1.1.0, v2.0.1, v2.1.0, v2.1.1].
    - Conclusion: install pestphp/pest-plugin v1.1.0 (conflict analysis result)
    
    Any attempts to cope with this end badly. Unable to update no pestphp no livewire no other dependencies.
 Tell me, is there at least some way to upgrade to Livewire 3?

**Comment by dcblogdev** [comment]
your best bet is to install a fresh copy using v4 I had to update a lot of the Livewire components for Livewire 3. To upgrade manually you can see the versions I've used in `composer.json` https://github.com/dcblogdev/laravel-admintw/blob/main/stubs/composer.json

**Comment by fixcoderu** [comment]
Thanks! I didn't see that a new version with Livewire 4 support was released. I installed it, everything works, thank you!

**Comment by liteshare92** [comment]
Hello,
Not really clear how to upgrade to livewire 3.
A how-to maybe.
Regards
