### ISSUE TITLE
Flash Message

### ISSUE THREAD

**Issue by vgoncalves13** [dcblogdev/laravel-admintw#30]
Hello,

In my tests, i realized that flash messages are not appearing.

I check app.blade.php layout and not find nothing to show the flashs messages.

So i include the errors.flash.blade.php in the app layout

```html

                <div class="px-7 py-5">
                    @include('errors.flash')
                    {{ $slot ?? '' }}
                </div>
```

I dont know if a missing something in docs about config flash message.

If you need i can do a PR.

Thanks.

**Comment by dcblogdev** [comment]
I believe this is by design, on pages that use Livewire components they may have their own notifications, on others such as the roles index I'll use `@include('errors.messages')` this will load any type of message including flash messages.

It's worth reviewing though.
