### ISSUE TITLE
Can't handel with a new permission

### ISSUE THREAD

**Issue by nael14** [dcblogdev/laravel-admintw#5]
Can't handel with a new permission

**Comment by dcblogdev** [comment]
What do you mean?

**Comment by nael14** [comment]
When Create a new permission not work successfully with can & cannot 
for example dd(cannot('show_menu'))   ==> return once true and another false (in livewire )

**Comment by dcblogdev** [comment]
all you need to do is add a permission to a seeder like this:

```php
Permission::firstOrCreate(['name' => 'view_tenants', 'label' => 'View Tenants', 'module' => 'App']);
```
then run `php artisan db:seed` since the permission is using a firstOrCreate its safe to run multiple times only 1 permission entry will be created.
