### ISSUE TITLE
Removal of User Registration

### ISSUE THREAD

**Issue by d7gonzo** [dcblogdev/laravel-admintw#7]
We would like to remove the user registration. Do you have any recommendations on moving forward with this? Would it be fairly easy to make it so invites could still be sent out to a curated set of users after making this change?

Any advice about possible solutions for this would be greatly appreciated. Thank you!

**Comment by dcblogdev** [comment]
Hi the simplest way would be to turn off the register routes in `routes/web.php`

```php
//    Route::get('register', [RegisterController::class, 'index'])->name('register');
//    Route::post('register', [RegisterController::class, 'store']);
```

This would turn off the register URL and also remove register button from the welcome page and login form.

You can then still invite users as normal.

**Comment by d7gonzo** [comment]
Great news. I was hoping it was that simple.

**Comment by dcblogdev** [comment]
yeah, the only entry point now is via the invites.
