### ISSUE TITLE
Laravel 9 and Vite

### ISSUE THREAD

**Issue by rabol** [dcblogdev/laravel-admintw#8]
Any plans on upgrading to Laravel 9 and Vite?

also it would be super cool that one could use the package as a admin package and not overwriting the normal Laravel app structure

**Comment by dcblogdev** [comment]
I think this already works with Laravel 9, for vite is I need the custom styles to work so will need to get vite to use the multiple style sheets via scss 

But yes I happy to upgrade this.

Currently it would replace the structure, I'll have to have a look at options.

**Comment by rabol** [comment]
Yes, I believe that it will work on a Laravel 9 project, however, new laravel projects uses Vite and as you say it will override the structure.

Small observation: you are the author of a Laravel module book, then I'm surprises to see that you did not build this package with modules in mind :-) :-) :-) :-)

**Comment by dcblogdev** [comment]
I was tempted to use modules but then I thought it may be better for this to be more open for people that don't use modules. 

I use this on my website I installed the theme and then installed modules to manage my blog posts and products.

**Comment by dcblogdev** [comment]
I working on a vite version, I've managed to get vite working with sass I should be able to get a release shortly.

**Comment by dcblogdev** [comment]
requires deeper testing before I merge in https://github.com/dcblogdev/laravel-admintw/pull/12/files

**Comment by dcblogdev** [comment]
this has now been merged in, 2.1 now uses vite instead of webpack.
